// Code generated by MockGen. DO NOT EDIT.
// Source: remora/internal/liquidity (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"
	liquidity "remora/internal/liquidity"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetSlot0 mocks base method.
func (m *MockRepository) GetSlot0(arg0 context.Context, arg1 *liquidity.PoolKey) (*liquidity.Slot0, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlot0", arg0, arg1)
	ret0, _ := ret[0].(*liquidity.Slot0)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlot0 indicates an expected call of GetSlot0.
func (mr *MockRepositoryMockRecorder) GetSlot0(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlot0", reflect.TypeOf((*MockRepository)(nil).GetSlot0), arg0, arg1)
}

// GetTickBitmap mocks base method.
func (m *MockRepository) GetTickBitmap(arg0 context.Context, arg1 *liquidity.PoolKey, arg2 int16) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickBitmap", arg0, arg1, arg2)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickBitmap indicates an expected call of GetTickBitmap.
func (mr *MockRepositoryMockRecorder) GetTickBitmap(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickBitmap", reflect.TypeOf((*MockRepository)(nil).GetTickBitmap), arg0, arg1, arg2)
}

// GetTickInfo mocks base method.
func (m *MockRepository) GetTickInfo(arg0 context.Context, arg1 *liquidity.PoolKey, arg2 int32) (*liquidity.TickInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTickInfo", arg0, arg1, arg2)
	ret0, _ := ret[0].(*liquidity.TickInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTickInfo indicates an expected call of GetTickInfo.
func (mr *MockRepositoryMockRecorder) GetTickInfo(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTickInfo", reflect.TypeOf((*MockRepository)(nil).GetTickInfo), arg0, arg1, arg2)
}
